GitHub Actions upgrades and improvements
* Use Maven 3.9.9
* Use macOS 15
* Use Ubuntu 24.04
* Verify there are no changed files

Signed-off-by: Wouter Born <github@maindrain.net>

diff --git a/.github/workflows/ci-build.yml b/.github/workflows/ci-build.yml
--- a/.github/workflows/ci-build.yml
+++ b/.github/workflows/ci-build.yml
@@ -19,8 +19,8 @@ jobs:
       fail-fast: false
       matrix:
         java: [ '11' ]
-        maven: [ '3.9.6' ]
-        os: [ 'macos-12', 'ubuntu-22.04', 'windows-2022' ]
+        maven: [ '3.9.9' ]
+        os: [ 'macos-15', 'ubuntu-24.04', 'windows-2022' ]
     name: Build (Java ${{ matrix.java }}, ${{ matrix.os }})
     runs-on: ${{ matrix.os }}
     steps:
@@ -69,3 +69,15 @@ jobs:
             -Dmaven.wagon.http.retryHandler.count=5
             -Dmaven.wagon.httpconnectionManager.ttlSeconds=25
             -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
+
+      - name: Verify Changed Files
+        uses: tj-actions/verify-changed-files@v20
+        id: verify-changed-files
+
+      - name: Fail on Changed Files
+        if: steps.verify-changed-files.outputs.changed_files != ''
+        env:
+          CHANGED_FILES: ${{ steps.verify-changed-files.outputs.changed_files }}
+        run: |
+          echo "::error::Files have changed: $CHANGED_FILES"
+          exit 1
